### ISSUE TITLE
Incorrect Canvas Locations In Generated Procedure

### ISSUE THREAD

**Issue by tsdobbs** [cclrobotics/ARTBot#60] opened 2020-02-24 07:33 UTC
When generating a procedure with 9 pieces of art, canvas locations were assigned in the following order:
1, 9, 3, 4, 5, 6, 7, 8
Slot 2 was missing, Slot 9 was listed in a suspicious place, and only 8 canvas locations were assigned.

Expected behavior is 1,2,3,4,5,6,7,8,9

**Comment by tsdobbs** [comment] 2020-02-24 07:35
One hypothesis - is it possible that two artpieces with the same title were loaded? (I'm specifically thinking of "HONK!", which had two versions). I think this would generate this behavior and also explain how we only had 8 artpieces in the end.

Recall that when this bug appeared we changed ```artpiece.slug``` to ```artpiece.title``` as a hotfix

**Comment by brcb20** [comment] 2020-02-24 16:52
> Recall that when this bug appeared we changed artpiece.slug to artpiece.title as a hotfix

Using artpiece.title when multiple artpieces have the same title is the cause of this bug and the reason we opted to use `artpiece.slug` instead. 
Issue #56 prevented you from using `artpiece.slug`. Once we have resolved that issue, this issue should resolve itself.

**Comment by brcb20** [comment] 2020-03-25 00:09
Closing this issue since it was solve by fixing #56

**Closed by brcb20** 2020-03-25 00:09 UTC
Labels: bug
